from __future__ import annotations

from typing import Any, Optional, Dict, List
from datetime import datetime

from pydantic import BaseModel, Field


class SkillMeta(BaseModel):
    """Metadata describing a skill exposed via MCP."""

    name: str = Field(..., description="Unique skill name")
    description: str | None = Field(None, description="Short description of the skill")
    version: str = Field("0.1.0", description="Skill semantic version")
    inputs: dict[str, Any] = Field(default_factory=dict, description="Input schema description")


class RunRequest(BaseModel):
    name: str
    args: dict[str, Any] = Field(default_factory=dict)


class RunResponse(BaseModel):
    success: bool
    result: Any | None = None
    error: str | None = None


class GenerateSkillRequest(BaseModel):
    """Request to generate a skill from natural language."""
    
    description: str = Field(..., description="Natural language description of what the skill should do")
    name: Optional[str] = Field(None, description="Optional suggested name for the skill")
    inputs: Optional[Dict[str, Any]] = Field(None, description="Optional input schema specification")


class GenerateSkillResponse(BaseModel):
    """Response with generated skill code and metadata."""
    
    success: bool = Field(..., description="Whether generation was successful")
    code: Optional[str] = Field(None, description="Generated Python code")
    meta: Optional[SkillMeta] = Field(None, description="Generated skill metadata")
    error: Optional[str] = Field(None, description="Error message if generation failed")


class RegisterSkillRequest(BaseModel):
    """Request to register a skill from code."""
    
    code: str = Field(..., description="Python code implementing the skill")
    meta: SkillMeta = Field(..., description="Metadata for the skill")


class RegisterSkillResponse(BaseModel):
    """Response to registering a new skill."""
    
    success: bool
    name: Optional[str] = None
    error: Optional[str] = None


class GetSkillCodeResponse(BaseModel):
    """Response containing a skill's source code."""
    
    name: str
    code: str


# New schema classes for Milestone 3

class ChatMessage(BaseModel):
    """A message in a chat session."""
    
    id: str = Field(..., description="Unique ID for the message")
    session_id: str = Field(..., description="ID of the session this message belongs to")
    role: str = Field(..., description="Role of the message sender (user, assistant, system)")
    content: str = Field(..., description="Message content")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the message was sent")
    skill_generated: Optional[str] = Field(None, description="Name of skill generated by this message, if any")


class ChatSession(BaseModel):
    """A chat session between a user and the AI."""
    
    id: str = Field(..., description="Unique ID for the session")
    name: str = Field(..., description="Display name for the session")
    created_at: datetime = Field(default_factory=datetime.now, description="When the session was created")
    updated_at: datetime = Field(default_factory=datetime.now, description="When the session was last updated")
    messages: List[ChatMessage] = Field(default_factory=list, description="Messages in the session")


class CreateSessionRequest(BaseModel):
    """Request to create a new chat session."""
    
    name: str = Field(..., description="Display name for the session")


class CreateSessionResponse(BaseModel):
    """Response to creating a new chat session."""
    
    session: ChatSession


class AddMessageRequest(BaseModel):
    """Request to add a message to a chat session."""
    
    role: str = Field(..., description="Role of the message sender (user, assistant, system)")
    content: str = Field(..., description="Message content")


class AddMessageResponse(BaseModel):
    """Response to adding a message to a chat session."""
    
    message: ChatMessage
    skill_generated: Optional[SkillMeta] = Field(None, description="Metadata for any skill generated by this message")
